# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MJOLNIR_GUI_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DataSet_filenames_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.DataSet_filenames_listWidget.setGeometry(QtCore.QRect(130, 110, 161, 151))
        self.DataSet_filenames_listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.DataSet_filenames_listWidget.setObjectName("DataSet_filenames_listWidget")
        item = QtWidgets.QListWidgetItem()
        self.DataSet_filenames_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.DataSet_filenames_listWidget.addItem(item)
        self.DataSet_convertData_button = QtWidgets.QPushButton(self.centralwidget)
        self.DataSet_convertData_button.setGeometry(QtCore.QRect(300, 240, 75, 23))
        self.DataSet_convertData_button.setObjectName("DataSet_convertData_button")
        self.DataSet_binning_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DataSet_binning_comboBox.setGeometry(QtCore.QRect(300, 210, 69, 22))
        self.DataSet_binning_comboBox.setObjectName("DataSet_binning_comboBox")
        self.DataSet_binning_comboBox.addItem("")
        self.DataSet_binning_comboBox.addItem("")
        self.DataSet_binning_comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 180, 71, 16))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 290, 176, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(210, 280, 114, 48))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 280, 61, 84))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 260, 61, 28))
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(410, 280, 51, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 110, 111, 151))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(130, 20, 111, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 50, 131, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(480, 280, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 260, 621, 111))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(420, 90, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(500, 40, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 70, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.View3D_plot_button = QtWidgets.QPushButton(self.groupBox)
        self.View3D_plot_button.setGeometry(QtCore.QRect(500, 80, 75, 23))
        self.View3D_plot_button.setObjectName("View3D_plot_button")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 370, 621, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 150, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(460, 90, 61, 42))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_9.setEnabled(True)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_4.addWidget(self.radioButton_9)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_4.addWidget(self.radioButton_8)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(460, 130, 91, 21))
        self.checkBox.setObjectName("checkBox")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(360, 20, 114, 48))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_5.addWidget(self.lineEdit_30, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 0, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_5.addWidget(self.lineEdit_31, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_15.setGeometry(QtCore.QRect(360, 70, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_32.setGeometry(QtCore.QRect(490, 20, 113, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_16.setGeometry(QtCore.QRect(490, 40, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(50, 10, 229, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 3, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_4.addWidget(self.lineEdit_20, 1, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_4.addWidget(self.lineEdit_19, 1, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_4.addWidget(self.lineEdit_21, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 3, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_4.addWidget(self.lineEdit_22, 3, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_4.addWidget(self.lineEdit_23, 3, 2, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_4.addWidget(self.lineEdit_24, 3, 3, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(50, 90, 216, 41))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 1, 0, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_8.addWidget(self.lineEdit_25, 1, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_8.addWidget(self.lineEdit_27, 1, 3, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_8.addWidget(self.lineEdit_26, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 0, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_34.setObjectName("label_34")
        self.gridLayout_8.addWidget(self.label_34, 0, 3, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(50, 140, 216, 22))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_36.setObjectName("label_36")
        self.gridLayout_9.addWidget(self.label_36, 0, 0, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_9.addWidget(self.lineEdit_28, 0, 1, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_9.addWidget(self.lineEdit_29, 0, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_37.setObjectName("label_37")
        self.gridLayout_9.addWidget(self.label_37, 0, 2, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setGeometry(QtCore.QRect(530, 110, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 720, 621, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_14.setGeometry(QtCore.QRect(110, 80, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 560, 621, 161))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 70, 61, 42))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_12.setEnabled(True)
        self.radioButton_12.setChecked(True)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_6.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_6.addWidget(self.radioButton_13)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(100, 20, 156, 41))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_35.setObjectName("label_35")
        self.gridLayout_10.addWidget(self.label_35, 1, 0, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_10.addWidget(self.lineEdit_47, 1, 1, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_10.addWidget(self.lineEdit_49, 1, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_10.addWidget(self.label_38, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 0, 2, 1, 1)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(100, 70, 111, 48))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_41.setObjectName("label_41")
        self.gridLayout_11.addWidget(self.label_41, 0, 0, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_11.addWidget(self.lineEdit_50, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_42.setObjectName("label_42")
        self.gridLayout_11.addWidget(self.label_42, 1, 0, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_11.addWidget(self.lineEdit_51, 1, 1, 1, 1)
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(340, 40, 114, 48))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_12.addWidget(self.lineEdit_48, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 1, 0, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_12.addWidget(self.lineEdit_52, 1, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_43.setObjectName("label_43")
        self.gridLayout_12.addWidget(self.label_43, 0, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_20.setGeometry(QtCore.QRect(490, 60, 75, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_53.setGeometry(QtCore.QRect(490, 30, 113, 20))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_5.setGeometry(QtCore.QRect(290, 110, 70, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_21.setGeometry(QtCore.QRect(540, 130, 75, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(410, 80, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 100, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(410, 120, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(410, 140, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(410, 160, 81, 16))
        self.label_14.setObjectName("label_14")
        self.DataSet_path_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.DataSet_path_lineEdit.setGeometry(QtCore.QRect(130, 80, 221, 20))
        self.DataSet_path_lineEdit.setObjectName("DataSet_path_lineEdit")
        self.groupBox_3.raise_()
        self.groupBox_5.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.DataSet_filenames_listWidget.raise_()
        self.DataSet_convertData_button.raise_()
        self.DataSet_binning_comboBox.raise_()
        self.label.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_8.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.listWidget_2.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.lineEdit_6.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.DataSet_path_lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMask = QtWidgets.QMenu(self.menubar)
        self.menuMask.setObjectName("menuMask")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_mask_gui = QtWidgets.QAction(MainWindow)
        self.actionOpen_mask_gui.setObjectName("actionOpen_mask_gui")
        self.actionLoad_mask = QtWidgets.QAction(MainWindow)
        self.actionLoad_mask.setObjectName("actionLoad_mask")
        self.actionGenerate_View3d_script = QtWidgets.QAction(MainWindow)
        self.actionGenerate_View3d_script.setObjectName("actionGenerate_View3d_script")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionGenerate_View3d_script)
        self.menuMask.addAction(self.actionOpen_mask_gui)
        self.menuMask.addAction(self.actionLoad_mask)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMask.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.DataSet_filenames_listWidget.isSortingEnabled()
        self.DataSet_filenames_listWidget.setSortingEnabled(False)
        item = self.DataSet_filenames_listWidget.item(0)
        item.setText(_translate("MainWindow", "filename1"))
        item = self.DataSet_filenames_listWidget.item(1)
        item.setText(_translate("MainWindow", "filename2"))
        self.DataSet_filenames_listWidget.setSortingEnabled(__sortingEnabled)
        self.DataSet_convertData_button.setText(_translate("MainWindow", "Convert Data"))
        self.DataSet_binning_comboBox.setToolTip(_translate("MainWindow", "Binning"))
        self.DataSet_binning_comboBox.setCurrentText(_translate("MainWindow", "8"))
        self.DataSet_binning_comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.DataSet_binning_comboBox.setItemText(1, _translate("MainWindow", "3"))
        self.DataSet_binning_comboBox.setItemText(2, _translate("MainWindow", "8"))
        self.label.setText(_translate("MainWindow", "Select binning"))
        self.label_4.setText(_translate("MainWindow", "E"))
        self.label_2.setText(_translate("MainWindow", "QX"))
        self.label_3.setText(_translate("MainWindow", "QY"))
        self.lineEdit_2.setText(_translate("MainWindow", "0.05"))
        self.lineEdit.setText(_translate("MainWindow", "0.05"))
        self.lineEdit_3.setText(_translate("MainWindow", "0.05"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "C axis max"))
        self.lineEdit_5.setText(_translate("MainWindow", "5e-6"))
        self.label_5.setText(_translate("MainWindow", "C axis min"))
        self.radioButton_2.setText(_translate("MainWindow", "Qx E"))
        self.radioButton.setText(_translate("MainWindow", "Qy E"))
        self.radioButton_3.setText(_translate("MainWindow", "Qx Qy"))
        self.label_7.setText(_translate("MainWindow", "Select view"))
        self.label_8.setText(_translate("MainWindow", "View3d bins"))
        self.radioButton_5.setText(_translate("MainWindow", "RLU"))
        self.radioButton_4.setText(_translate("MainWindow", "AA-1"))
        self.label_9.setText(_translate("MainWindow", "Units"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Data set 1"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "Data set 2"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_6.setText(_translate("MainWindow", "New data set"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete data set"))
        self.pushButton_10.setText(_translate("MainWindow", "Add files to data set"))
        self.pushButton_11.setText(_translate("MainWindow", "Delete files from data set"))
        self.lineEdit_6.setText(_translate("MainWindow", "My title"))
        self.groupBox.setTitle(_translate("MainWindow", "View 3d"))
        self.checkBox_3.setText(_translate("MainWindow", "Log scale"))
        self.pushButton_12.setText(_translate("MainWindow", "Set title"))
        self.pushButton_3.setText(_translate("MainWindow", "Set c axis"))
        self.View3D_plot_button.setText(_translate("MainWindow", "Plot View3D"))
        self.groupBox_2.setTitle(_translate("MainWindow", "QE line"))
        self.pushButton_4.setText(_translate("MainWindow", "Plot 2d cut"))
        self.radioButton_9.setText(_translate("MainWindow", "RLU"))
        self.radioButton_8.setText(_translate("MainWindow", "AA-1"))
        self.checkBox.setText(_translate("MainWindow", "Constant bins"))
        self.lineEdit_30.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "C axis max"))
        self.lineEdit_31.setText(_translate("MainWindow", "5e-6"))
        self.label_23.setText(_translate("MainWindow", "C axis min"))
        self.pushButton_15.setText(_translate("MainWindow", "Set c axis"))
        self.lineEdit_32.setText(_translate("MainWindow", "My title"))
        self.pushButton_16.setText(_translate("MainWindow", "Set title"))
        self.label_20.setText(_translate("MainWindow", "Start"))
        self.label_21.setText(_translate("MainWindow", "End"))
        self.lineEdit_20.setText(_translate("MainWindow", "0"))
        self.lineEdit_19.setText(_translate("MainWindow", "0"))
        self.lineEdit_21.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "H"))
        self.label_19.setText(_translate("MainWindow", "K"))
        self.label_17.setText(_translate("MainWindow", "L"))
        self.lineEdit_22.setText(_translate("MainWindow", "1"))
        self.lineEdit_23.setText(_translate("MainWindow", "0"))
        self.lineEdit_24.setText(_translate("MainWindow", "0"))
        self.label_31.setText(_translate("MainWindow", "Energy"))
        self.label_32.setText(_translate("MainWindow", "Min"))
        self.label_33.setText(_translate("MainWindow", "Max"))
        self.label_34.setText(_translate("MainWindow", "N points"))
        self.label_36.setText(_translate("MainWindow", "Width"))
        self.lineEdit_28.setText(_translate("MainWindow", "0.1"))
        self.lineEdit_29.setText(_translate("MainWindow", "0.03"))
        self.label_37.setText(_translate("MainWindow", "Min pixel"))
        self.checkBox_4.setText(_translate("MainWindow", "Log scale"))
        self.groupBox_3.setTitle(_translate("MainWindow", "1d stuff"))
        self.pushButton_13.setText(_translate("MainWindow", "Simple plot"))
        self.pushButton_14.setText(_translate("MainWindow", "Make cut"))
        self.pushButton_5.setText(_translate("MainWindow", "Make fit"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Q plane"))
        self.radioButton_12.setText(_translate("MainWindow", "RLU"))
        self.radioButton_13.setText(_translate("MainWindow", "AA-1"))
        self.label_35.setText(_translate("MainWindow", "Energy"))
        self.lineEdit_47.setText(_translate("MainWindow", "1"))
        self.lineEdit_49.setText(_translate("MainWindow", "2"))
        self.label_38.setText(_translate("MainWindow", "Min"))
        self.label_39.setText(_translate("MainWindow", "Max"))
        self.label_41.setText(_translate("MainWindow", "QX width"))
        self.lineEdit_50.setText(_translate("MainWindow", "0.03"))
        self.label_42.setText(_translate("MainWindow", "QY width"))
        self.lineEdit_51.setText(_translate("MainWindow", "0.03"))
        self.lineEdit_48.setText(_translate("MainWindow", "0"))
        self.label_40.setText(_translate("MainWindow", "C axis max"))
        self.lineEdit_52.setText(_translate("MainWindow", "5e-6"))
        self.label_43.setText(_translate("MainWindow", "C axis min"))
        self.pushButton_20.setText(_translate("MainWindow", "Set title"))
        self.lineEdit_53.setText(_translate("MainWindow", "My title"))
        self.checkBox_5.setText(_translate("MainWindow", "Log scale"))
        self.pushButton_21.setText(_translate("MainWindow", "Plot 2d cut"))
        self.label_10.setText(_translate("MainWindow", "Temperature"))
        self.label_11.setText(_translate("MainWindow", "Magnetic field"))
        self.label_12.setText(_translate("MainWindow", "Sample name"))
        self.label_13.setText(_translate("MainWindow", "Scan command"))
        self.label_14.setText(_translate("MainWindow", "Type of scan"))
        self.DataSet_path_lineEdit.setText(_translate("MainWindow", "Path/To/Current/Directory/"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMask.setTitle(_translate("MainWindow", "Mask"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_mask_gui.setText(_translate("MainWindow", "Open mask gui"))
        self.actionLoad_mask.setText(_translate("MainWindow", "Load mask"))
        self.actionGenerate_View3d_script.setText(_translate("MainWindow", "Generate View3d script"))
